import { atomWithImmer } from "jotai-immer"
import { PlotType } from "plotly.js"

// export const tracesAtom = atomWithImmer<Data[]>([])
export const tracesAtom = atomWithImmer<{ id: string; type?: PlotType; x?: string; y?: string; secondaryY: boolean }[]>(
  [],
)

export const PlotTypeArray = [
  "bar",
  // "barpolar",
  // "box",
  // "candlestick",
  // "carpet",
  // "choropleth",
  // "choroplethmapbox",
  // "cone",
  // "contour",
  // "contourcarpet",
  // "densitymapbox",
  // "funnel",
  // "funnelarea",
  // "heatmap",
  // "heatmapgl",
  // "histogram",
  // "histogram2d",
  // "histogram2dcontour",
  // "image",
  // "indicator",
  // "isosurface",
  // "mesh3d",
  // "ohlc",
  // "parcats",
  // "parcoords",
  // "pie",
  // "pointcloud",
  // "sankey",
  "scatter",
  // "scatter3d",
  // "scattercarpet",
  // "scattergeo",
  // "scattergl",
  // "scattermapbox",
  // "scatterpolar",
  // "scatterpolargl",
  // "scatterternary",
  // "splom",
  // "streamtube",
  // "sunburst",
  // "surface",
  // "table",
  // "treemap",
  // "violin",
  // "volume",
  // "waterfall",
]
